import { HEADERS_TYPE } from './types';

export const BASE_URL: string = 'https://my.arlo.com';
export const AUTH_URL: string = 'https://ocapi-app.arlo.com';
export const API_URL: string = `https://myapi.arlo.com`;

export const ROUTES: any = {
    LOGIN: `${AUTH_URL}/api/auth`,
    LOGOUT: `${API_URL}/hmsweb/logout`,
    GET_FACTORS: `${AUTH_URL}/api/getFactors`,
    START_AUTH: `${AUTH_URL}/api/startAuth`,
    FINISH_AUTH: `${AUTH_URL}/api/finishAuth`,

    DEVICE_BASE: `${API_URL}/hmsweb/users/devices`,
    GET_DEVICES: `${API_URL}/hmsweb/users/devices`,

    GET_FRIENDS: `${API_URL}/hmsweb/users/friends`,
    MODIFY_FRIEND: `${API_URL}/hmsweb/users/friends`,
    ADD_FRIEND: `${API_URL}/hmsweb/users/friends`,
    REMOVE_FRIEND: `${API_URL}/hmsweb/users/friends/remove`,

    GET_ACCOUNT: `${API_URL}/hmsweb/users/account`,
    GET_PROFILE: `${API_URL}/hmsweb/users/profile`,
    GET_SESSION: `${API_URL}/hmsweb/users/session/v2`, //v1 route returns error
    GET_DEVICE_LOCATIONS: `${API_URL}/hmsweb/users/locations`,

    CHANGE_EMAIL: `${AUTH_URL}/api/updateEmailCombined`,
    CHANGE_PASSWORD: `${API_URL}/hmsweb/users/changePassword`,
    UPDATE_PROFILE: `${API_URL}/hmsweb/users/profile`,
    SET_PRIMARY_FACTOR: `${AUTH_URL}/api/setPrimaryFactor`,
    START_PAIRING_FACTOR: `${AUTH_URL}/api/startPairingFactor`,
    FINISH_PAIRING_FACTOR: `${AUTH_URL}/api/finishPairingFactor`,
    REMOVE_FACTOR: `${AUTH_URL}/api/removeFactor`,

    SET_DEVICE_NAME: `${API_URL}/hmsweb/users/devices/renameDevice`,

    SUBSCRIBE_TO_STREAM: `${API_URL}/hmsweb/client/subscribe`,
    NOTIFY_DEVICE: `${API_URL}/hmsweb/users/devices/notify/`,

    RESTART_BASESTATION: `${API_URL}/hmsweb/users/devices/restart`,
};

export const APP_EVENTS: any = {
    BODY_CLICK: "body_click",
    BODY_KEY_DOWN: "body_key_down",
    BODY_MOUSE_UP: "body_mouse_up",
    TAKE_SNAPSHOT: "take_snapshot",
    SNAPSHOT_LOADED: "snapshot_loaded",
    SHOW_ERROR: "show_error",
    HIDE_ERROR: "hide_error",
    CAMERA_BUSY: "camera_busy",
    CAMERA_ERROR: "camera_error",
    CAMERA_ADDED: "camera_added",
    CAMERA_IDLE: "camera_idle",
    BRIGHTNESS_UPDATED: "brightness_updated",
    RSSI_UPDATED: "rssi_updated",
    MAPLE_ALARMSATE_UPDATED: "maple_alarmstate_updated",
    BS_REBOOTED: "bs_rebooted",
    MEDIA_UPLOAD_NOTIFICATION: "mediaUploadNotification",
    RECORD_DELETED: "RecordDeleted",
    TIMELINE_PLAY: "timeline_play",
    TIMELINE_STOP: "timeline_stop",
    NOT_LIVE_TIMELINE_STOP: "not_live_timeline_stop",
    ACTIVE_ZONE_EDIT: "zone_edit",
    ACTIVE_ZONE_ADD: "zone_add",
    ZOOM_EDIT: "zoom_edit",
    ZOOM_SAVE: "zoom_save",
    ZOOM_RESET: "zoom_reset",
    ZOOM_UPDATED: "zoom_updated",
    SIREN_STATE_UPDATED: "siren_state_updated",
    LIBRARY_UPDATED: "library_updated",
    TOGGLE_SLIDER: "toggleSlider",
    TOGGLE_CAMERA_CONTROL: "toggleCameraControl",
    SHOW_ARLO_SMART_TRIAL: "show_arlo_smart_trial",
    AUDIO_PLAYBACK_STATUS: "audio_playback_status",
    SLIDER_START_DRAG: "slider_start_drag",
    SLIDER_STOP_DRAG: "slider_stop_drag",
    USAGE_THRESHOLD: "usage_threshold",
    CHARGING_STATE_UPDATE: "charging_state_update",
    CHARGER_TECH_UPDATE: "charger_tech_update",
    E911_SETUP_COMPLETE: "e911_setup_complete",
    E911_CALL: "e911_call",
    LOCATIONS_UPDATE: "locations_update",
    LOCATIONS_INIT: "locations_init",
    LOCATIONS_CHANGED: "locations_changed",
    ON_LOCATIONS_CHANGE: "on_locations_change",
    RECORDING_STOPPED: "recordingStopped",
    MODES_UPDATED: "modes_updated",
    ALERTS_BAR_TOP: "alerts_bar_top",
    ALERTS_BAR_BACK: "alerts_bar_back",
    ALERTS_BAR_FS: "alerts_bar_fs",
    LOADING_START: "loading",
    LOADING_STOP: "loaded",
    AUDIO_PLAYBACK_START: "audio_playback_start",
    AUDIO_PLAYBACK_STOP: "audio_playback_stop",
    SLIDER_UPDATE: "slider_update",
    UPDATE_PIR_DIAGRAM: "update_pir_diagram",
    UPDATE_USER_PROFILE: "update_user_profile",
    UN_CLAIM_DEVICES: "un_claim_devices",
    UPDATE_SPOTLIGHT: "update_spotlight",
    ARLO_SMART_UPDATE: "arlo_smart_update",
    SOUND_PLAYER_DESTROY: "sound_player_destroy",
    GATEWAY_POLLING_START: "gateway_polling_start",
    GATEWAY_POLLING_SHUTDOWN: "gateway_polling_shutdown",
    GATEWAY_POLLING_SUCCESS: "gateway_polling_success",
    PUSH_HANDLER_INIT: "push_handler_init",
    PUSH_HANDLER_SHUTDOWN: "push_handler_shutdown",
    PTT_BTN_CLICK: "PTT_BTN_CLICK",
    CHECK_OFFLINE_COMPLETE: "check_offline_complete",
    REMIND_QUICK_STREAM_OFF: "remind_quick_stream_off",
    DISABLE_BABY_EDU_TOUR: "disable_baby_edu_tour",
    CALL_NO_SHARING_SERVICES: "call_no_sharing_services",
    MEDIA_LABEL_UPDATED: "media_label_updated",
    PTT_STOP: "ptt_stop",
    KF_LABEL_ADDED: "kf_label_added",
    KF_LABEL_REMOVED: "kf_label_removed",
    KF_IMAGE_REMOVED: "kf_image_removed",
    KF_FR_LABEL_UPDATED: "kf_fr_label_updated",
    KF_FR_LABEL_DELETED: "kf_fr_label_deleted",
    KF_FR_IMAGE_UPDATED: "kf_fr_image_updated",
    KF_FR_IMAGE_DELETED: "kf_fr_image_deleted",
    MQTT_POLLING_START: "mqtt_polling_start",
    MQTT_NOTIFY: "mqtt_notify",
    MQTT_LOGOUT: "mqtt_logout",
    MQTT_ERROR: "mqtt_error",
    MQTT_END: "mqtt_end",
    CLAIMED_DEVICE: "CLAIMED_DEVICE",
    SHOW_TOOLTIP: "show_tooltip",
    HIDE_TOOLTIP: "hide_tooltip",
    BEFORE_UNLOAD: "onbeforeunload",
    OPEN_SHUTTER: "openShutter",
    CLOSE_SHUTTER: "closeShutter",
    PLAN_WILL_CONTINUE: "plan_will_continue",
    SUCCESS_MESSAGE: "success_message",
    BASESTATION_LOCALCERT: "basestation_localCert",
    ERROR_RED_ALERT: "error_red_alert",
    CMDRESULT: "cmdResult",
    ERASE_PROGRESS_UPDATE: "eraseProgressUpdate",
    RANGE_FINDER_STATE_UPDATED: "rangeFinderStateUpdated",
    PINS_RECEIVED: "pinsReceived",
    DEVICE_ACTIONS: ["recordActiveMotionVideo","recordSnapshot","sendEmailAlert"],
    DEVICE_TRIGGERS: ["motionDetect","lowBattery","lowSignalStrength"],
    STORAGE_STATUS: {
        NOT_PRESENT: "NotPresent",
        NOT_MOUNTED: "NotMounted",
        MOUNTING: "Mounting",
        UN_MOUNTING: "Unmounting",
        FORMATTING: "Formatting",
        ERASING: "Erasing",
        READY: "Ready",
        NOT_PARTITIONED: "NotPartitioned",
        NOT_MOUNTABLE: "NotMountable",
        NOT_WRITABLE: "NotWritable",
        IO_ERROR: "IOError",
        INSUFFICIENT_SPACE: "InsufficientSpace",
        UNAVAILABLE: "Unavailable"
    },
    STORAGE_UI_STATUS: {
        FORMAT: "format",
        SPACE: "space",
        LOW_SPACE: "lowspace"
    }
}

export const AUTH_HEADERS: HEADERS_TYPE = {
    'DNT': '1',
    'schemaVersion': '1',
    'Auth-Version': '2',
    'Content-Type': 'application/json; charset=UTF-8',
    'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B202 NETGEAR/v1 (iOS Vuezone)',
    'Origin': `${BASE_URL}`,
    'Referer': `${BASE_URL}/`,
    'Source': 'arloCamWeb',
    'TE': 'Trailers',
};